# Generated by Django 5.0.6 on 2024-06-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plates',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('emission_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plates',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('prod_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=10, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('plate_number', models.ForeignKey(blank=True, db_column='platenumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_revisions.plates')),
            ],
            options={
                'db_table': 'revisions',
            },
        ),
        migrations.AddField(
            model_name='plates',
            name='vehicle_number',
            field=models.ForeignKey(blank=True, db_column='vehiclenumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_revisions.vehicle'),
        ),
        migrations.CreateModel(
            name='Inactiveplates',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('emission_date', models.DateField(blank=True, null=True)),
                ('res_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.ForeignKey(blank=True, db_column='vehiclenumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_revisions.vehicle')),
            ],
            options={
                'db_table': 'inactiveplates',
            },
        ),
        migrations.CreateModel(
            name='Activeplates',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('emission_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.ForeignKey(blank=True, db_column='vehiclenumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_revisions.vehicle')),
            ],
            options={
                'db_table': 'activeplates',
            },
        ),
    ]
