# Generated by Django 5.0.6 on 2024-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_revisions', '0002_rename_activeplates_activeplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revision_date',
            field=models.DateField(blank=True, db_column='revision_date', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prod_date',
            field=models.DateField(blank=True, db_column='prod_date', null=True),
        ),
    ]
