# Generated by Django 5.0.6 on 2024-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_revisions', '0003_alter_revision_revision_date_alter_vehicle_prod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revision_date',
            field=models.DateField(blank=True, db_column='revisiondate', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prod_date',
            field=models.DateField(blank=True, db_column='proddate', null=True),
        ),
    ]
